### ISSUE TITLE
List 20 possible topics/pages for the atlas

### ISSUE THREAD

**Issue by clemsos** [theatlasofdata/theatlasofdata.earth#16]
We should maintain a list of open topics that we are interested in so people can jump in or we can hammer it ourselves one after another

**Comment by clemsos** [comment]
See also #33 for existing databases

**Comment by margocargo** [comment]
ideas for content : 
— seed vaults (localization, actors, preservation, database) 
— territorial and international waters (from fishing area to servers and data storing)
— fake snow in winter sport station (impacts on phreatic zone)
— map of the mineral ressources and soil type 
— the internet undersea world
— geocode systems

**Comment by clemsos** [comment]
Replaced by #47 .
