### ISSUE TITLE
Move out of iframe to embed visualization?

### ISSUE THREAD

**Issue by clemsos** [theatlasofdata/theatlasofdata.earth#40]
Currently we are using an iframe

https://github.com/theatlasofdata/theatlasofdata.earth/blob/c8e01d13f66240c4b46f9f7af93e4554e11661e4/_layouts/post.html#L20

Will it be better to directly embed the svg?

@makio135 ideas?

**Comment by MAKIO135** [comment]
> Will it be better to directly embed the svg?

Don't think so: it would need to generate the svg first, meaning loading the the viz & rendering it in a separate context to avoid dependencies version problems, and that would make the viz less interactive (no more JS events)

**Comment by clemsos** [comment]
True. I was asking because we have very few control about how things shows up in an iframe VS an embed viz in the page.

Maybe we need a `viz.html` template where we have a bunch of defined variables (like `width`, `height`, etc) so we can have proper support for mobile (#39) as well as coherent color schemes and VI across the different viz (see https://github.com/theatlasofdata/visual-identity/issues/2).

**Comment by clemsos** [comment]
For now, let's archive all viz in repo. No 3rd part, iframe or other unreliable solutions

can fetch from blo.cks.org using https://www.npmjs.com/package/blockfetcher
