### ISSUE TITLE
Make atlas references a post

### ISSUE THREAD

**Issue by clemsos** [theatlasofdata/theatlasofdata.earth#45]
Need to store refs in a data file and make a timeline or map out of it

**Comment by clemsos** [comment]
Right now living unlinked at https://theatlasofdata.earth/what-is-an-atlas

**Comment by WalterRobin** [comment]
Platform Anthropocene -> https://www.planthro.org/ 
+
State of the Climate 2018 -> https://wmo.maps.arcgis.com/apps/Cascade/index.html?appid=855267a7dd394825aa8e9025e024f163
